config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/fair-epos-prototype
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/deephdc/DEEP-OC-generic-dev:
      branch: master
      repo: https://github.com/deephdc/DEEP-OC-generic-dev
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/deephdc/DEEP-OC-generic-dev git:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-coral-rat.sh
        container: qc.acc_bluesy-brown-boar
  QC.Doc:
    repos:
      github.com/deephdc/DEEP-OC-generic-dev find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-amber-worm.sh
        container: qc.doc_craggy-orange-angelfish
      github.com/deephdc/DEEP-OC-generic-dev git:
        commands:
        - /usr/bin/env sh .sqa/script.ready-brown-goat.sh
        container: qc.doc_skimpy-asparagus-gopher
      github.com/deephdc/DEEP-OC-generic-dev markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-cornflower-llama.sh
        container: qc.doc_seedy-grey-dunker
  QC.Lic:
    repos:
      github.com/deephdc/DEEP-OC-generic-dev licensee:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-pumpkin-gharial.sh
        container: qc.lic_hasty-persimmon-booby
  QC.Sty:
    repos:
      github.com/deephdc/DEEP-OC-generic-dev hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-cyan-fowl.sh
        container: qc.sty_wheezy-blue-zorse
      github.com/deephdc/DEEP-OC-generic-dev jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-indigo-bombay.sh
        container: qc.sty_scanty-cyan-koala
  QC.Ver:
    repos:
      github.com/deephdc/DEEP-OC-generic-dev get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-chocolate-okapi.sh
        container: qc.ver_whiny-azure-fish
timeout: 5400
