config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/deephdc/DEEP-OC-generic-dev:
      branch: master
      repo: https://github.com/deephdc/DEEP-OC-generic-dev
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/deephdc/DEEP-OC-generic-dev git:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-smalt-dalmatian.sh
        container: qc.acc_muzzy-eggplant-squid
  QC.Doc:
    repos:
      github.com/deephdc/DEEP-OC-generic-dev find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-zucchini-moth.sh
        container: qc.doc_tacky-ultramarine-emu
      github.com/deephdc/DEEP-OC-generic-dev git:
        commands:
        - /usr/bin/env sh .sqa/script.surly-cream-lionfish.sh
        container: qc.doc_sunny-firebrick-monster
  QC.Lic:
    repos:
      github.com/deephdc/DEEP-OC-generic-dev licensee:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-smalt-owl.sh
        container: qc.lic_craggy-peach-orangutan
  QC.Ver:
    repos:
      github.com/deephdc/DEEP-OC-generic-dev get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-khaki-whale.sh
        container: qc.ver_gloppy-wheat-armadillo
timeout: 5400
